### ISSUE TITLE
Name of custom badges isn't getting set by lang file

### ISSUE THREAD

**Issue by CarsonF** [NoahY/q2a-badges#12]
I just changed line 21 in qa-badge-admin.php from `return qa_lang('badges/'.$slug);` to `return qa_badge_name($slug);`

Saw you had made this change recently in other places :)

**Comment by CarsonF** [comment]
Hmm maybe I'm missing something. qa_register_plugin_phrases doesn't allow you to register the same name twice, so I used 'custom_badges'. Without the change I made, the badge name I specify doesn't show up in admin options. Instead it says `[badges/test_gold]`, however the description does get changed to what I specify. Am I doing something wrong?

**Comment by NoahY** [comment]
Sorry, you're right... my mistake, I was looking at qa_badge_lang().  I don't think it matters to make the change, but I'll do it anyway.

As for your problem, I think it requires you to set a string in your phrases file as "badge_<your_badge_slug>".  The badges plugin only picks up strings that start with "badge_", so it shouldn't be a problem with duplicates.  As per the readme:

3. implement **qa_register_plugin_phrases()** via your qa-plugin.php, including two entries for each badge: _badge_<slug>_ and _badge_<slug>_desc_.  Here is an example from the comment-voting plugin:

```
return array(
    'permit_vote_c' => 'Vote on comments',
    'badge_nice_comment' => 'Nice Comment',
    'badge_good_comment' => 'Good Comment',
    'badge_great_comment' => 'Great Comment',
    'badge_nice_comment_desc' => 'Comment received +# upvote',
    'badge_good_comment_desc' => 'Comment received +# upvote',
    'badge_great_comment_desc' => 'Comment received +# upvote',
);
```

**Comment by CarsonF** [comment]
I do have the **badge_** prefix in my array and the description one was getting picked up, just not the name.
I read the readme to mean I needed to call the qa_register_plugin_phrases() in my qa_plugin.php. Is this not the case?
I have this, which works:
`qa_register_plugin_phrases('qa-custom-badges-lang-default.php', 'custom_badges');`
But q2a won't let me define **badges** twice, hence **custom_badges**. Am I wrong here?

**Comment by NoahY** [comment]
Ah, I think I know what your problem is... see, the badges plugin saves the names in qa_opt, so that you can edit the names as you like in admin (you can do that by clicking on a badge in the admin panel).  Once they are saved, it will no longer pick them up from qa_lang, so you have to do it there, or else click the "reset badge names" button in admin.

I think that is the issue you are facing.

**Comment by CarsonF** [comment]
I think that was the issue. Thanks for sorting this. Great plugin btw.
