### ISSUE TITLE
Any dependencies when updating from v2.2 to latest v3.9?

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#14]
Hi Noah, before updating the badges plugin I would like to know if I can expect any errors.

I know that there are dependencies, such as:  

Badges language string, dependency in [q2a-history-plugin](https://github.com/NoahY/q2a-history/blob/master/qa-history-layer.php), qa-history-layer.php, line 414: 

`$badge_name=qa_badge_name($slug);`

// before: 
`$badge_name=qa_lang('badges/'.$slug); // eetv: former badges version needs 'badges/'`

What changes has been implemented? Where do I need to take care?

_Table qa_userbadges has not changed its structure, so this for instance would be fine._

Thanks,
Kai

**Comment by NoahY** [comment]
Hi Kai,

I don't think there should be any dependencies - I wasn't aware of the 
history plugin dependency.

Best wishes,

Yuttadhammo

**Comment by echteinfachtv** [comment]
Thanks for letting me know, will update soon :)
