### ISSUE TITLE
Updating from v2.2 to latest v3.9 - New values not saving

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#16]
Hi NoahY, 

I updated the badges plugin to 3.9 and ran into some issues, maybe it is important for others to note them down: 
1. Before changing language strings in qa-badge-lang-default.php switch texteditor's encoding to UTF-8 without BOM
2. Dependency in [q2a-history-plugin](https://github.com/NoahY/q2a-badges/issues/14)
3. After the update values for achievements, e.g. "x^answers of users were..." → x values get all reset to default?!

How can I solve n°3? I tried to enter the new values, hit save, nothing was saved. Just showing default values. What could be the reason?

All the best,
Kai

Edit: 
Possible duplicate of: https://github.com/NoahY/q2a-badges/issues/15

**Comment by echteinfachtv** [comment]
Added: If I see it right, in my database "qa_options" holds the correct numbers, e.g. badge_good_question_var = 4, however, admin panel shows another value (in this case 5, the default value). 

I guess: `$badge_desc=qa_badge_desc_replace($slug,@$info['var'],true);`
is responsible for getting the values. 

In v2.2 it was: `$badge_desc=qa_badge_desc_replace($slug);`

Cannot see the error.

**Reading the new values and showing them to the admin seems not working, it takes the default values.**

**Comment by NoahY** [comment]
fixed in latest code - it was saving, I think, just not showing in admin.

**Comment by echteinfachtv** [comment]
https://github.com/NoahY/q2a-badges/commit/d43708dad525734016d84ac01b2569964ede9ae0#qa-badge-admin.php

it is working again, be blessed :)
