### ISSUE TITLE
Updating from v2.2 to latest v3.9 - New database fields in qa_options?

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#17]
I just saw that there is a new field for every existing badge with empty value: 

from v2.2:
`('badge_famous_question_desc', ''),
('badge_famous_question_enabled', '1'),
('badge_famous_question_name', 'Beliebte Frage+++'),
('badge_famous_question_var', '1000'),`

from v3.9:
`**('badge_famous_question', ''),**
('badge_famous_question_desc', ''),
('badge_famous_question_enabled', '1'),
('badge_famous_question_name', 'Beliebte Frage+++'),
('badge_famous_question_var', '1000'),`

What is this extra field for?

**Comment by NoahY** [comment]
thanks, this was due to a typo in the code that was creating these extra 
fields.  fixed now.

**Comment by echteinfachtv** [comment]
So I can remove these fields from qa_options again?

**Comment by NoahY** [comment]
yep - they're useless.

**Comment by echteinfachtv** [comment]
well then ;)
