### ISSUE TITLE
Rechecking badge awarding: Undefined index in /badges/qa-badge-admin.php on line 891

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#18]
About 600 error messages in my error log, 12:49 am: 

`Undefined index: name in /badges/qa-badge-admin.php on line 891`
`Undefined index: website in /badges/qa-badge-admin.php on line 891`
`Undefined index: location in /badges/qa-badge-admin.php on line 891`
`Undefined index: about in /badges/qa-badge-admin.php on line 891`

Error comes up when doing >`Admin` >`Recheck Badge awarding`!

_badges-plugin-version: 3.9_

**Comment by NoahY** [comment]
should be fixed now

**Comment by echteinfachtv** [comment]
Did the recheck, works fine! merci!

However, got "profile completed" i.e. 'profiler' badges even for empty profiles.
Ticket: https://github.com/NoahY/q2a-badges/issues/20
