### ISSUE TITLE
javascript function badgeEdit(slug,end) on each page - necessary?

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#19]
On every page - it does not matter if you are logged in or not - in the html source there is the function: `function badgeEdit(slug,end)`

Maybe we can only output that for admin? ... as the badge edit should be only for admin :)

... or is that the badge notifier? But why is it called badgeEdit then?

Thank you :+1: 
Kai

**Comment by NoahY** [comment]
fixed - this was my first q2a plugin, back when I was feeling my way in 
the dark :) it's amazing it actually works...

**Comment by echteinfachtv** [comment]
https://github.com/NoahY/q2a-badges/commit/7c6d651e0ce0d24d006d9ff2ab629b935099cff6#qa-badge-layer.php

thank you!

**Comment by echteinfachtv** [comment]
''this was my first q2a plugin''

... and it is one of the best ones for q2a!
