### ISSUE TITLE
Undefined variable: oids

### ISSUE THREAD

**Issue by svivian** [NoahY/q2a-badges#2]
I get this notice when viewing a user page. On investigation it's coming from qa-badge-layer.php, around line 440. Notice goes away if you change this:

```
if(qa_opt('badge_show_source_posts')) {
    $oids = @$info['oid'];
}
```

to this:

```
if(qa_opt('badge_show_source_posts')) {
    $oids = @$info['oid'];
}
else
    $oids = null;
```

**Comment by NoahY** [comment]
Great, thanks.  The badge plugin was the first thing I wrote for Q2A, 
and I'm still not a programming expert, so you'll probably see it's a 
bit of a hack in many places.
