### ISSUE TITLE
Profiler badge assigned even for empty profiles

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#20]
After rechecking the badges, I see 'profiler' badges ("profile completed") even for empty profiles.

Example: http://www.gute-mathe-fragen.de/badges (see "Profil vollständig", click on user "gidgreen" who has no fields completed)

Can we only grant the profiler badge if **all default fields** have information?
- Full Name
- Location
  [- Website] _optional_
- Description

See fields in `qa_userprofile` column `title`.

Have a good Sunday!
Kai

**Comment by NoahY** [comment]
can you try rebuilding the list using the latest code?

**Comment by echteinfachtv** [comment]
Now it works as expected, badge only awarded if profile is completely filled :)
thank you for the fix!
