### ISSUE TITLE
Default Badge Names not loading from language file

### ISSUE THREAD

**Issue by firelite** [NoahY/q2a-badges#21]
I assume the badge names (i.e.,'badges/good_question', 'badges/grateful', etc)   should automatically be replaced by names listed within qa-badge-lang-default.php, but the past two releases has not addressed this issue.  

Clicking the 'Reset Names' does not load default names from the lang file nor does it reset manually inputted names.

**Comment by NoahY** [comment]
Thank you, sorry for the delay, I've fixed this in the latest code.
