### ISSUE TITLE
Fatal error: Allowed memory size..

### ISSUE THREAD

**Issue by levelingup** [NoahY/q2a-badges#23]
I'm getting this error:

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 29189 bytes)

How do I fix this? I tried looking at the closed issues, but it doesn't seem to work, and now this error pops up again. Any thoughts?

**Comment by danisetyanto** [comment]
i have same problem

**Comment by danisetyanto** [comment]
problem resolve
https://github.com/NoahY/q2a-badges/pull/3

**Comment by levelingup** [comment]
I don't get it though, they merged the pull request. Doesn't that mean that the code is already within the current script?

**Comment by danisetyanto** [comment]
do you have try the svivian code?
https://github.com/svivian/q2a-badges/archive/master.zip

**Comment by Darkheir** [comment]
I Have the exact same error, but only on the admin widget page when qa-badges is loaded.

For what I know the error come from the following code:

```
foreach ($badges as $slug => $info) {
                $badge_name=qa_badge_name($slug);
                if(!qa_opt('badge_'.$slug.'_name')) {
                    qa_opt('badge_'.$slug.'_name',$badge_name);
                }
                $name = qa_opt('badge_'.$slug.'_name');

                $badge_desc=qa_badge_desc_replace($slug,qa_opt('badge_'.$slug.'_var'),true);
                $type = qa_get_badge_type($info['type']);
                $types = $type['slug'];

                $fields[] = array(
                        'type' => 'static',
                        'note' => '<table class="badge-listing"><tr><td><input type="checkbox" name="badge_'.$slug.'_enabled"'.(qa_opt('badge_'.$slug.'_enabled') !== '0' ? ' checked':'').'></td><td><input type="text" name="badge_'.$slug.'_edit" id="badge_'.$slug.'_edit" style="display:none" size="16" onblur="badgeEdit(\''.$slug.'\',true)" value="'.$name.'"><span id="badge_'.$slug.'_badge" class="badge-'.$types.'" onclick="badgeEdit(\''.$slug.'\')" title="'.qa_lang('badges/badge_admin_click_edit').'">'.$name.'</span></td><td>'.$badge_desc.'</td></tr></table>'
                );
            }
```

**Comment by NoahY** [comment]
Try updating to latest code and let me know if it is fixed.

**Comment by blizeH** [comment]
Hi Noah,

Thanks for looking into this, unfortunately I have the same problem, although it doesnt display the error on my host

I'm running the latest version - happy for you to have admin access to my site if you need to test anything

Thanks :)

**Comment by Darkheir** [comment]
Here's my post on stackoverflow about this problem: http://stackoverflow.com/questions/13849492/allowed-memory-size-exhausted-but-memory-get-peak-usage-says-otherwise.
The answer provided by Danack could be the reason of the problem don't you think?

**Comment by Arech** [comment]
2all: Check issue #31, there may be solution you need.

**Comment by NoahY** [comment]
please try latest code, thanks Arach.
