### ISSUE TITLE
Apache Crashes when Badges merges arrays from custom_badges();  Bookmarks and Comment Voting plugins affected

### ISSUE THREAD

**Issue by firelite** [NoahY/q2a-badges#24]
So here's how to reproduce the crash or error: 
- Install Q2A
- Install and activate Badges plugin
- Install Comment Voting plugin
- Navigate to Admin >> Plugins control panel

I have been trying to debug this for quite some time.  The crash seems to be caused when qa_get_badge_list() merges arrays from custom_badges() methods within Bookmarks and Comment Voting plugins or any other implementations of Custom Badges.  With some echoing, I could see that qa_get_badge_list() is infinitely and recursively being called when an array_merge() is successful; whereas, if array_merge() never merges anything and $badges only contains the default badges, there will be no errors.

[badges file: qa-plugin.php]

function qa_get_badge_list() {
...
        $badges=array_merge($badges,$module->custom_badges());
...
}

[comment voting file: qa-comment-voting-admin.php]

function custom_badges() {
    return array(
        'nice_comment' => array('var'=>2, 'type'=>0),
        'good_comment' => array('var'=>5, 'type'=>1),
        'great_comment' => array('var'=>10, 'type'=>2)
    );
}

Essentially, if you comment out the 3 array entries (returning an empty array), apache won't crash or throw an error, but obviously, Custom Badges just won't work as promised.   It was be really nice to get this working.  Thanks.

**Comment by NoahY** [comment]
thanks, should be fixed, no?
