### ISSUE TITLE
Suggestion for Badge page: Use comma instead BR to list users

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#28]
Having 400+ users who verified their email address gives a long user list that you have to scroll a lot. 

Suggestion: List all users comma separated instead each user on one line. 

To do that, change **qa-badge-page.php** line 103 from: 

`$qa_content['custom'.$c] .= implode('<br/>',$users).'</div>';`

to:

`$qa_content['custom'.$c] .= implode(', ',$users).'</div>';`

Thanks and merry xmas to all =)

**Comment by NoahY** [comment]
fixed.
