### ISSUE TITLE
Test notification is not closeable

### ISSUE THREAD

**Issue by Arech** [NoahY/q2a-badges#32]
You won't be able to close notification bar after clicking "Test notify" button within a /admin/plugins

This happens because onclick handler is invalid `jQuery(this).parent()..slideUp()`
Replace it to `jQuery(this).parent().parent().slideUp()` in `qa-badge-layer.php::function trigger_notify($message)`.

What's the state of **Master** branch of this plugin? Look like it is extremely unstable, is there a stable well-tested version available?

**Comment by NoahY** [comment]
fixed, thanks.

Sorry, wysiwyg :)
