### ISSUE TITLE
Wrong URL in "badge awarded" notification

### ISSUE THREAD

**Issue by Arech** [NoahY/q2a-badges#33]
When "Show badges on main profile field (not badges tab) " is set, notification bar makes wrong URL to user profile, using `?tab=badges` GET parameter instead of something like `#badges`

**Comment by Arech** [comment]
Here is possible solution. Need to update `qa-badge-layer.php::function badge_notify()`. Find `if(count($result) > 0){` clause and put after it

``` php
$bNoTab = !!qa_opt('badge_admin_user_field_no_tab');
$anchorToAccountBadges = '<a href="'
    . qa_path_html(
        'user/' . qa_get_logged_in_handle()
        , $bNoTab ? null : array('tab' => 'badges'),
        qa_opt('site_url')
    ) . ($bNoTab ? '#badge-form' : '')
    . '">';
```

Then use defined `$anchorToAccountBadges` when constructing long `$notice .=` assignment later.

**NB**: it is possible that there was another bug, because anchor construction algorithm was different for different notifications count. It should be the same, isn't it?

Looks like I'm not going to report next bugs I'll find, - I've already found too much of them for a one day. The code doesn't look finished and well-tested... It takes too much time to report all of them(I'm not native English speaker), while I'm not sure it is even welcomed.

Good luck

**Comment by NoahY** [comment]
fixed now, thanks.  Yes, it's welcome, but I'm not a professional developer, just needed a plugin for my site.  Feel free to fork and suggest commits, that's the most helpful.
