### ISSUE TITLE
Badges watchdog, bloodhound, pitbull set to 0 after "Recheck Badge Awarding"

### ISSUE THREAD

**Issue by echteinfachtv** [NoahY/q2a-badges#34]
Hi Noah,

Today I have realized that the badges for flagging inappropriate posts (watchdog, bloodhound, pitbull) are set to 0 after I used "Recheck Badge Awarding" in admin panel. 

I regularly delete flagged posts, that could be the reason. 

I could not see yet, how you count flags / events for flags. 

Do you know any solution?

Thanks!
Kai

**Comment by NoahY** [comment]
Sorry, I'm away from the computer these days... I'm pretty sure flags are
in the votes table with userid associated with the flag, so it just takes
those.

**Comment by echteinfachtv** [comment]
ah I remember, before deleting the flagged post I removed the "is spam" flags from the post. This is the reason why they lost their badges! Thanks :)

_closed_
