### ISSUE TITLE
Badge widget not displaying correctly at two places

### ISSUE THREAD

**Issue by techmynd** [NoahY/q2a-badges#35]
Plugin Options:
1- Show badge widget beside points in user meta
(does not show up)
2- Show badge widget beside points in question list
gives an error something like Undefined index:  .......qa-include/qa-app-format.php(1466) : eval()'d code - at user profile in recent activity questions.
Also page for badges is not displaying correctly.

I am using latest version of this plugin with Q2A 1.5.4.

Great great plugin but needs fixes.

Thanks

**Comment by techmynd** [comment]
Explanation:
No.1. When user logs in. At the top, in header it says: 
hello HiroshiRana (# points)
I want this to be HiroshiRana ●5 ●5 ●5
This is not being changed even when I select "Show badge widget beside points in user meta" from plugin admin.

**Comment by techmynd** [comment]
No.2 
In user profile - the URL is like: qasite.com/user/username
In that url I have 
- user details
- activity by user
- recent activity by user
- badges

in recent activity by user - there is list of questions  and its like

question title
asked 58 minutes ago in Arts

Now there the error apears if i check "Show badge widget beside points in question list" from badges admin  

All other questions lists are showing ●5 ●5 ●5 instead of user points except user meta in user logged in section which i mentioned in previous comment.

I want this like > ●5 ●5 ●5 at every place besides user name instead of user points.

**Comment by techmynd** [comment]
- And the badge page (pages) is not displaying correctly (no css, no badges) 
- Recent badges widget in sidebar also not displaying.

**Comment by techmynd** [comment]
Let me show you at live site...

badges page: smashingsolution.com/badges/

user profile page error: smashingsolution.com/user/superadmin
see in Recent activity by superadmin

and Recent Badge Widget is also active from page layout for sidebar top
but not displaying

and logged in user welcome name reflects points, where it should reflect badge dots.

**Comment by NoahY** [comment]
I'll have to look at the widget later... the rest should be fixed in latest code

**Comment by techmynd** [comment]
Thanks a lot.
