### ISSUE TITLE
Several badges not awarding correctly

### ISSUE THREAD

**Issue by svivian** [NoahY/q2a-badges#5]
Some of the badges don't appear to be given to the right people. No one on my site appears to be awarded the "Verified Human" badge, but everyone should have their email verified (you need that in order to post).

"Club" badges are wrong also. I set up "1k Club", "10k Club" and "100k Club" with 1,000, 10,000 and 100,000 points respectively. But it's only awarded the first 2 badges to my account, whereas I have 8 members over 10k and 45 users over 1k.

**Comment by NoahY** [comment]
On 09/05/2011 04:37 AM, svivian wrote:

> Some of the badges don't appear to be given to the right people. No one on my site appears to be awarded the "Verified Human" badge, but everyone should have their email verified (you need that in order to post).

Yeah, I couldn't get verified human to actually work; then I forgot 
about it :)  I'll take a look now to see how it actually works.

> "Club" badges are wrong also. I set up "1k Club", "10k Club" and "100k Club" with 1,000, 10,000 and 100,000 points respectively. But it's only awarded the first 2 badges to my account, whereas I have 8 members over 10k and 45 users over 1k.
> This is strange... it works fine for me... it's taking the points from 
> the ^userpoints table; maybe you can check and make sure that the points 
> there are as they should be?

Another problem seems to be with the total days visited and consecutive 
days visited... I think my method of calculating that is wrong.

**Comment by svivian** [comment]
Email verification can be found by getting the "flags" field from the user table. The code `$flags & QA_USER_FLAGS_EMAIL_CONFIRMED` will be 1 if the user has confirmed their email or 0 otherwise. Note it's a single ampersand which does a "bitwise operation" (a little complex to explain, it often confuses me). So you can basically do:

```
if ( $flags & QA_USER_FLAGS_EMAIL_CONFIRMED ) {
    // give them the badge
}
```

I checked my userpoints table and the "points" field has all the right points totals, so not sure what the problem there is. I will investigate and let you know :)

**Comment by svivian** [comment]
OK I found the issue with the Club badges - they're only checked on users listed in the achievements table. Since I'm the only person logged in on my test site, it's only added me.

On a real site the users would be visiting the site and getting put into the achievements table so this is probably not a big issue.

**Comment by NoahY** [comment]
Ah, right... that's okay, I can separate them out; the issue is that the 
rebuild function is most useful for your type of case, where the admin 
of an existing site wants to add the badge plugin and have a 
prepopulated list of badges; otherwise, everyone gets these notices 
popping up that they're in all three clubs at once.

I'll just separate it out into two queries instead.

**Comment by NoahY** [comment]
Yeah, I figured it out and patched it up; should work now both when 
users verify and when you run the rebuild routine.
