### ISSUE TITLE
Undefined Index after disabling custom badges plugin

### ISSUE THREAD

**Issue by scottcher** [NoahY/q2a-badges#9]
I had created a custom badges plugin which added three new badges but with the recent problems with the badges plugin, I disabled it, along with your badges plugin.  Only one user (me) had been awarded any of the custom badges I'd created - just the bronze one.

Now, when trying to re-enable the your badges plugin without my badges plugin being installed, I get an undefined index error:

Notice: Undefined index: searcher in C:\apps\question2answer\qa-plugin\q2a-badges\qa-plugin.php on line 163

Line 163 in your badges code is:

```
function qa_get_badge_type_by_slug($slug) {
    $badges = qa_get_badge_list();
    return qa_get_badge_type($badges[$slug]['type']);
```

This is obviously because my custom badges plugin isn't installed and its found the one badge that was awarded that was part of that custom badge plugin but shouldn't the code be more robust and not complain that it can't find the badge any longer and just skip over it instead of reporting the error in the output stream?

**Comment by NoahY** [comment]
"shouldn't the code be more robust" 

of course it should be :) it was my first q2a plugin, though, and a pretty complicated one at that.  I'll put some fix in for this...

**Comment by NoahY** [comment]
should be fixed now.

**Comment by scottcher** [comment]
Lolz - sorry, I could have been more... I could have found a better way to say that. =)

I like plugin very much.  I am having issues building a custom badges plugin, however (My first!).  I think its choking on the qa_*_lang_default.php file I created, however.  I think I'm doing it the way you did it in the comment-voting plugin but when I add my custom plugin, the admin page goes completely blank.  When I comment out the 

if(function_exists('qa_register_plugin_phrases')){
    qa_register_plugin_phrases('qa-sb-lang-*.php', 'searcher_badges');
}

lines in my qa-plugin.php, the admin page loads but my new badges show up without a valid description or input form for the award thresholds:

```
searcher    [badges/searcher_desc]
researcher  [badges/researcher_desc]
investigator    [badges/investigator_desc]
```

The same thing happened to the names, but you mentioned I should Reset Names to get them to appear and they now do.

My default language file looks like this:

```
// array of default phrases (for localization)
return array(
    'badge_searcher' => 'Searcher',
    'badge_researcher' => 'Researcher',
    'badge_investigator' => 'Investigator',
    'badge_searcher_desc' => 'Performed # searches',
    'badge_researcher_desc' => 'Performed # searches',
    'badge_investigator_desc' => 'Performed # searches',
}; // array()
```

That's just an open assignment inside the php tag.  I sure could use some pointers here...

**Comment by scottcher** [comment]
Wow, thanks for the quick fix for the issue.  Hopefully you are still online and can offer a quick tip for my other issue.

**Comment by scottcher** [comment]
Wow, nevermind.  I found my error.  Should have seen it in the output I posted above but didn't and my editor is making it hard to see there too - guess I'm getting old, my eye's are as good as they used to be.  return array(} isn't proper...  gads - how long did I spend looking for something more insidious than a syntax mistake!
